name: Deploy Cloudflare Worker

on:
  push:
    branches:
      - main  # Change to your default branch if it's not 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y curl jq

    - name: Parse wrangler.toml and deploy
      env:
        CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
      run: |
        # Parse the wrangler.toml file to get the script name
        SCRIPT_NAME=$(grep -Po '(?<=name = ").*(?=")' wrangler.toml)
        SCRIPT_PATH=$(grep -Po '(?<=main = ").*(?=")' wrangler.toml)
        
        # Create the deployment payload
        WORKER_SCRIPT=$(cat $SCRIPT_PATH)
        echo "$WORKER_SCRIPT" > worker-script.js

        # Deploy the Worker
        curl -X PUT "https://api.cloudflare.com/client/v4/accounts/$CF_ACCOUNT_ID/workers/scripts/$SCRIPT_NAME" \
          -H "Authorization: Bearer $CF_API_TOKEN" \
          -H "Content-Type: application/javascript" \
          --data-binary @worker-script.js
