name: Deploy with Wrangler

on:
  push:
    branches:
      - main  # Change to your default branch if it's not 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Specify the Node.js version you need

    - name: Install wrangler
      run: npm install -g @cloudflare/wrangler

    - name: Authenticate Wrangler
      env:
        CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
      run: wrangler login --api-token $CF_API_TOKEN

    - name: Run wrangler deploy
      run: wrangler deploy
